version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "(GHA)"
    reviewers:
      - "UKHomeOffice/core-cloud-devops"
    labels:
      - "dependencies"
      - "patch"
  - package-ecosystem: "terraform"
    directory: "/modules/aws/group_account_assignments"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "(TF)"
    reviewers:
      - "UKHomeOffice/core-cloud-devops"
    labels:
      - "dependencies"
      - "patch"
  - package-ecosystem: "terraform"
    directory: "/modules/aws/group_user_memberships"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "(TF)"
    reviewers:
      - "UKHomeOffice/core-cloud-devops"
    labels:
      - "dependencies"
      - "patch"
  - package-ecosystem: "terraform"
    directory: "/modules/aws/groups"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "(TF)"
    reviewers:
      - "UKHomeOffice/core-cloud-devops"
    labels:
      - "dependencies"
      - "patch"
  - package-ecosystem: "terraform"
    directory: "/modules/aws/ssoadmin_instance"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "(TF)"
    reviewers:
      - "UKHomeOffice/core-cloud-devops"
    labels:
      - "dependencies"
      - "patch"
  - package-ecosystem: "terraform"
    directory: "/modules/aws/users"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "(TF)"
    reviewers:
      - "UKHomeOffice/core-cloud-devops"
    labels:
      - "dependencies"
      - "patch"
