formatter: markdown

output:
  file: README.md
  mode: inject

content: |
  # Terraform Module for - fetching secrets from secrets manager
  # Example terragrunt.hcl inputs 
  ```hcl
  inputs = {
    secret_name = "dev/splunk/hec-token"  # example secret-name to fetch its secret value
  }
  ```
  {{ .Providers }}
  {{ .Requirements }}
  {{ .Resources }}
  {{ .Inputs }}
  {{ .Outputs }}
  {{ .Footer }}
settings:
  sections:
    - header
    - providers
    - requirements
    - resources
    - inputs
    - outputs
    - footer
