name: SAST Scans

on:
  workflow_call:
    secrets:
      sonar_token:
        required: true
      sonar_host_url:
        required: true
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write
  actions: read
  security-events: write

jobs:
  checkov-scan:
    uses: UKHomeOffice/core-cloud-workflow-checkov-sast-scan/.github/workflows/checkov-scan-base.yaml@1.9.0

  sonarqube-scanner:
    name: SonarQube Code Analysis
    uses: UKHomeOffice/core-cloud-workflow-sonarqube-scan/.github/workflows/sonarqube-scan.yaml@1.1.3
    secrets:
      sonar_token: ${{ secrets.sonar_token }}
      sonar_host_url: ${{ secrets.sonar_host_url }}
