name: 'SemVer Tag on Main Merge'
on:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  pull-requests: read
  contents: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  semver-tag:
    name: 'Tag Repository with SemVer'
    if: |
      github.event.pull_request.merged == true &&
      contains(github.event.pull_request.labels.*.name, 'skip-release') == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Parse the SemVer label
        id: label
        uses: UKHomeOffice/match-label-action@v1
        with:
          labels: minor,major,patch
          mode: singular

      - name: Calculate SemVer value
        id: calculate
        uses: UKHomeOffice/semver-calculate-action@v2
        with:
          increment: ${{ steps.label.outputs.matchedLabels }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PEM_FILE }}

      - name: Tag Repository
        uses: UKHomeOffice/semver-tag-action@v4
        with:
          tag: ${{ steps.calculate.outputs.version }}
          github_token: ${{ steps.app-token.outputs.token }}
