name: Validate Terraform with Trivy

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  RunTerraformValidation:
    name: Run Terraform Validation
    runs-on: ubuntu-latest

    steps:
      - name: Clone the Repository
        uses: actions/checkout@v4

      # Results have to be a table as the organisation does not have Advanced Security license.
      - name: Run Trivy against Terraform
        uses: aquasecurity/trivy-action@0.18.0
        with:
          scan-type: 'config'
          exit-code: '1'
